### ISSUE TITLE
It also gets rid of my visual studio command prompt  and git bash pinned shortcuts and other stuff along the way. 

### ISSUE THREAD

**Issue by bach001** [ionuttbara/windows-defender-remover#108] opened 2023-11-29 00:39 UTC
As said in the title. Command prompt setting also changed. Windows PowerShell looks like a different version NOW! Did I opt the wrong option to run? -_-

**Comment by ionuttbara** [comment] 2023-12-08 12:01
can you detail what **Windows PowerShell looks like a different version NOW!** means?

**Comment by bach001** [comment] 2023-12-09 16:50
> can you detail what **Windows PowerShell looks like a different version NOW!** means?

I am on windows 11 let me give you a snapshot

![image](https://github.com/ionuttbara/windows-defender-remover/assets/33710058/33a016a7-7ad9-469d-855a-2d3b469ba9ef)

if right click on the title bar, it clearly shows that it is different from its original installation. if you have windows 11, the difference is very obvious.

![image](https://github.com/ionuttbara/windows-defender-remover/assets/33710058/a23def26-0a4e-4532-afcb-a13ff3e3cad0)

**Comment by ionuttbara** [comment] 2023-12-10 15:16
noted as bug.. trying to get into it. if the bug is caused by script, will be fixed and a method will be found for you.

**Comment by ionuttbara** [comment] 2023-12-24 15:02
fixed in 12.6.3.

**Closed by ionuttbara** 2023-12-24 15:02 UTC
Labels: bug
